version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Senac123"
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/database-docker:/var/lib/postgresql/data 
  redis:
    image: redis
    command: redis-server --requirepass Senac123
    ports:
      - "6379:6379"